project-viable/viable-virtual-lab

- project/source/Scripts/Objects/GelMoldVariant.gd
Moved LabLog warns so that they are actually called
> Added check for contents when button pressed

- project/source/Scenes/Objects/ElectrolysisSetup.tscn
- project/source/Scripts/Objects/ElectrolysisSetup.gd
Remove "Fill" above electrolysis setup and fixed issue of graduated cylinder getting stuck in front of it.
> 138 fill text above gel rig

- docs/index.md
- docs/reference/objectslot.md
- project/source/Scenes/Objects/ElectrolysisSetup.tscn
- project/source/Scenes/Objects/GelImager.tscn
- project/source/Scenes/Objects/ObjectSlot.tscn
- project/source/Scripts/Objects/ElectrolysisSetup.gd
- project/source/Scripts/Objects/GelImager.gd
- project/source/Scripts/Objects/ObjectSlot.gd
Also did some refactoring for the ObjectSlot and made the signal function name more generic.
> 152 need to add objectslot to documentation

- project/source/Modules/GelElectrophoresis.tres
- project/source/Scripts/Objects/GelWell.gd
Add the 50 microliter limit for DNA substance
Left out the ~270mL for filling the ElectrolysisSetup for now, since that would involve changing how that object works which is too close to the deadline now.
> 64 correct parameters volumes etc

- project/source/Scripts/Objects/GelWell.gd
- project/source/Scripts/Objects/Pipette.gd
@tylerhand1, hopefully reviewing this should just require a quick run through of the lab, to make sure I'm not missing anything obvious?
> Pipette overdraw

- project/source/Mixtures.gd
The file object was renamed to File Access. I added some more error checking and types to all the variables
> 200 file object fixes

- project/source/Scripts/Objects/GraduatedCylinder.gd
- project/source/Scripts/UI/Camera.gd
There were no signals in the code base, however there was a single instance of pressed that did not get changed to button_pressed by the auto updater.
> 189 - BaseButton

- project/source/Main.gd
- project/source/Scripts/Logger/ProcedureChecker.gd
- project/source/Scripts/Objects/CurrentSource.gd
- project/source/Scripts/Objects/Disposal.gd
- project/source/Scripts/Objects/ObjectSlot.gd
- project/source/Scripts/Resources/ModuleData.gd
> Fix most @export type declarations

- project/source/Scripts/Objects/Microwave.gd
> Fix `Microwave::heatTime` type

- project/source/Scripts/Objects/ElectrodeTerminal.gd
- project/source/Scripts/Objects/ElectrolysisSetup.gd
> Fix `ElectrolysisSetup::current_source`

- project/source/Scripts/Objects/GelMoldSubsceneManager.gd
- project/source/Scripts/Objects/Scale.gd
- project/source/Scripts/Objects/WeighBoat.gd
> Change some uses of `weight` to `mass`

- project/source/Scripts/Objects/ElectrodeTerminal.gd
- project/source/Scripts/Objects/ElectrolysisSetup.gd
- project/source/Scripts/Objects/Microwave.gd
- project/source/Scripts/Objects/ObjectSlot.gd
> Fix signatures of `TryInteract` in various places and make sure all paths return

- project/source/Scripts/Objects/LabObject.gd
- project/source/Scripts/Objects/Pipette.gd
The pipettes no longer fall down when you let go of them, resolves #236
> fixed issue where pipettes were being affected by gravity

- project/source/Main.tscn
- project/source/Scenes/Objects/Scale.tscn
- project/source/Scenes/Objects/Scoopula.tscn
- project/source/Scripts/Objects/GelMoldSubsceneManager.gd
- project/source/Scripts/Objects/LabObject.gd
- project/source/Scripts/Objects/Scale.gd
- project/source/Scripts/Objects/Scoopula.gd
- project/source/Scripts/Objects/UI/ScoopulaMenu.gd
- project/source/Scripts/Objects/WeighBoat.gd
These changes include fixes for some of the physics and gravity related bugs as well as some of the UX bugs with menu functionality being broken for the scale and scoopula menus.
Closes #239 and possibly #238
> gel mold collision bug (+ other bugs)

- project/source/Main.tscn
- project/source/Modules/FluorescenceMicroscopy.tres
After having the instructions for this procedure approved by others, I added them into the instructions tab.
> Instructions have been added to the instructions tab.

- project/source/Modules/FluorescenceMicroscopy.tres
Users must turn off the microscope light before making a cell image.
> Added a step to the instructions

- docs/procedures/fluorescence_microscopy.md
- docs/procedures/gel_electrophoresis.md
- docs/procedures/index.md
- project/source/Main.tscn
- project/source/Modules/FluorescenceMicroscopy.tres
I updated the instructions to include the play button now that color combo channels have been implemented.
> updated instructions

- project/source/Scenes/Modules/FluorescenceMicroscopy.tscn
- project/source/Scenes/Objects/Computer.tscn
- project/source/Scenes/Objects/computer.gd
- project/source/Scenes/UI/ChannelsPanel.tscn
- project/source/Scenes/UI/PowerExposure.tscn
- project/source/Scenes/UI/macro_panel.gd
- project/source/Scripts/UI/PowerAndExposure.gd
- project/source/UI/ButtonNormalStylebox.tres
- project/source/UI/MainUITheme.tres
- Redid the Macro Panel
- Fixed Channel Panel and Combo Channel UI elements
Resolves #309
> Fix and refine the UI and panels in the microscope program

- project/source/combined_scenes/flask.tscn
- project/source/combined_scenes/graduated_cylinder.tscn
- project/source/combined_scenes/microcentrifuge_tube.tscn
- project/source/updated_assets/lab_objects/erlenmeyer_flask.svg
- project/source/updated_assets/lab_objects/erlenmeyer_flask.svg.import
- project/source/updated_assets/lab_objects/graduated_cylinder.svg
- project/source/updated_assets/lab_objects/graduated_cylinder.svg.import
- project/source/updated_assets/lab_objects/microcentrifuge_tube.svg
- project/source/updated_assets/lab_objects/microcentrifuge_tube.svg.import
Udated these objects to the correct transparent sprites:
- Flask
- Graduated Cylinder
- Microcentrifuge Tube
> Update Sprites to be Transparent

- project/source/combined_scenes/power_supply.tscn
- project/source/combined_scripts/power_supply.gd
- project/source/combined_scripts/time_line_edit.gd
- project/source/combined_scripts/time_line_edit.gd.uid
- project/source/combined_scripts/voltage_line_edit.gd
- project/source/combined_scripts/voltage_line_edit.gd.uid
- Users can now type in the desired time or voltage on the power supply for convenience sake
> Typing Functionality to Time and Voltage on Power Supply
